config:
  device: cpu
  layout: True
  formula: True
  table_config:
    is_table_recog_enable: False
    max_time: 400

weights:
  layout: Layout/model_final.pth
  mfd: MFD/weights.pt
  mfr: MFR/UniMERNet
  table: TabRec/StructEqTable